// config.js
const fs = require("fs");
require("dotenv").config();

const config = {
  SESSION_ID: process.env.SESSION_ID || "BABIYA-MD [KILL]>>>eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiNkpQVlQ2eHRmdVQyM1VqVnpEazFCS3FVNkpHVGMvWmdwbjYzZUpNU3drdz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiK2xGOGFuSE1FQjBxdXdNUnN1TS8ralI2UEtxZHBZbFBhdi9OOFFIVVlXZz0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiIwRnUzM0t4d3I1VHYvNmJERTQxRU42T1JkR0R1aWpPNjJyK0RoUWxuNzNBPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJvK01YNU9iYXc2TTBvR2k4VU9UU3ZSOSs3dElpdGZqL1UwejNJTjhTQUVrPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkFFSHE3YVo3Q0pQSDFqYU9HbGl5NzJQbmFhMFQ0Uk1ZNFpza3B5TXBSMGM9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6InlMbWRTNGl2OVQxSmRLQ21vZjI1a2w0dy92dFk4RE1KRElxNzFYY1hUMXc9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoicVB2d1pERnk3Y2gyQTh3V0syMFFRUTRNZXpYTlM2ZDBNRFNjVFZFVWkyQT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiOWozQ21IM2NUaE05enJObFBSKytHV0NuY09MdmhSRzlkb0Y2cUpQVjJHVT0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IlBIcHdxc2EzcHJJR3NjSHl3a3JSMnVnc1pSQndvbERjNlF1Q3dKeHdQUVZEb2E3ZlFOdkZUams2b3h6Y1FEOWxpck9tb0U3bTBsMk5MRDFTN0JRd2h3PT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6OTEsImFkdlNlY3JldEtleSI6Ikhjd3I4UGU0RDY3b3QrbWVmdTNOSHBrdHYyWmc4OVllK2NsMElPY1NXS0E9IiwicHJvY2Vzc2VkSGlzdG9yeU1lc3NhZ2VzIjpbXSwibmV4dFByZUtleUlkIjozMSwiZmlyc3RVbnVwbG9hZGVkUHJlS2V5SWQiOjMxLCJhY2NvdW50U3luY0NvdW50ZXIiOjAsImFjY291bnRTZXR0aW5ncyI6eyJ1bmFyY2hpdmVDaGF0cyI6ZmFsc2V9LCJkZXZpY2VJZCI6IkZHSXNqSjlfU0MyTHFXd1g1a0RUdUEiLCJwaG9uZUlkIjoiNzEwMzAwY2EtM2E1OS00ZWUyLWJmNzEtYmE0ZmQyMDcwZTFlIiwiaWRlbnRpdHlJZCI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6InlLempvcXk1ckFpYUFGSitML2E0U1VNYkhsZz0ifSwicmVnaXN0ZXJlZCI6dHJ1ZSwiYmFja3VwVG9rZW4iOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJCWTJDMEZDM2x5dFdmNHlLK0M4VXVjL0g4SWc9In0sInJlZ2lzdHJhdGlvbiI6e30sInBhaXJpbmdDb2RlIjoiSzY4MzJRN0ciLCJtZSI6eyJpZCI6Ijk0NzY1NjM3NzU2OjNAcy53aGF0c2FwcC5uZXQiLCJuYW1lIjoi8J2Xo/Cdl6LwnZeX8J2XnPCdl6zwnZeUIn0sImFjY291bnQiOnsiZGV0YWlscyI6IkNOakNoWVFDRUpqTGtNRUdHQUVnQUNnQSIsImFjY291bnRTaWduYXR1cmVLZXkiOiIwNGR0NzdRWXh2MklOaXU4N0ZBcDFYUXNVYzRRTWsrNWNkOXJhNnprQUFFPSIsImFjY291bnRTaWduYXR1cmUiOiJoTjY4STdLQ2xjb3ZLbTFqRUJMb0JLb2lpeTRiSWlRTzVDSVVqQUkwbzlTcWRNTVBNeXFOWXhORUJYOVF3aUcxUGJLTHN0aXYrRWpNSmlObW44YmRCQT09IiwiZGV2aWNlU2lnbmF0dXJlIjoiaURtRVpDTThrWjczSmVHWUVXVUVzb3JQdHFDRThiWWhSWkZJMkwyTjRIRWpVc1NTbUxISXczTzBpWXhuQkM0OGNVMityYnFiNlVSQzAybzZvVFZuaFE9PSJ9LCJzaWduYWxJZGVudGl0aWVzIjpbeyJpZGVudGlmaWVyIjp7Im5hbWUiOiI5NDc2NTYzNzc1NjozQHMud2hhdHNhcHAubmV0IiwiZGV2aWNlSWQiOjB9LCJpZGVudGlmaWVyS2V5Ijp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQmRPSGJlKzBHTWI5aURZcnZPeFFLZFYwTEZIT0VESlB1WEhmYTJ1czVBQUIifX1dLCJwbGF0Zm9ybSI6InNtYmEiLCJsYXN0QWNjb3VudFN5bmNUaW1lc3RhbXAiOjE3NDcxOTkzOTgsIm15QXBwU3RhdGVLZXlJZCI6IkFBQUFBRjI3In0=",
  PREFIX: process.env.PREFIX || '.',
  AUTO_STATUS_READ: process.env.AUTO_STATUS_READ !== undefined ? process.env.AUTO_STATUS_READ === 'true' : true, 
  AUTO_STATUS_REPLY: process.env.AUTO_STATUS_REPLY !== undefined ? process.env.AUTO_STATUS_REPLY === 'false' : false,
  STATUS_READ_MSG: process.env.STATUS_READ_MSG || '',
  AUTO_DL: process.env.AUTO_DL !== undefined ? process.env.AUTO_DL === 'true' : false,
  AUTO_READ: process.env.AUTO_READ !== undefined ? process.env.AUTO_READ === 'true' : false,
  AUTO_TYPING: process.env.AUTO_TYPING !== undefined ? process.env.AUTO_TYPING === 'true' : false,
  AUTO_RECORDING: process.env.AUTO_RECORDING !== undefined ? process.env.AUTO_RECORDING === 'true' : true,
  ALWAYS_ONLINE: process.env.ALWAYS_ONLINE !== undefined ? process.env.ALWAYS_ONLINE === 'true' : true,
  AUTO_REACT: process.env.AUTO_REACT !== undefined ? process.env.AUTO_REACT === 'true' : false,
   /*auto block only for 212 */
  AUTO_BLOCK: process.env.AUTO_BLOCK !== undefined ? process.env.AUTO_BLOCK === 'true' : true,
  
  
  REJECT_CALL: process.env.REJECT_CALL !== undefined ? process.env.REJECT_CALL === 'true' : false, 
  NOT_ALLOW: process.env.NOT_ALLOW !== undefined ? process.env.NOT_ALLOW === 'true' : true,
  MODE: process.env.MODE || "private",
  OWNER_NAME: process.env.OWNER_NAME || "BABIYA-MD",
  OWNER_NUMBER: process.env.OWNER_NUMBER || "94764978991",
  GEMINI_KEY: process.env.GEMINI_KEY || "AIzaSyCUPaxfIdZawsKZKqCqJcC-GWiQPCXKTDc",
  WELCOME: process.env.WELCOME !== undefined ? process.env.WELCOME === 'true' : false, 
};


module.exports = config;
